name: CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
      BUNDLE_PACKAGES__NOCOFFEE__FR: ${{ secrets.BUNDLE_GITHUB__COM }}
      MAGLEV_ADMIN_USERNAME: ${{ secrets.MAGLEV_ADMIN_USERNAME }}
      MAGLEV_ADMIN_PASSWORD: ${{ secrets.MAGLEV_ADMIN_PASSWORD }}      
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Tag
        id: tag
        run: |
          echo "tag=$(git rev-parse "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: 
          secrets: |
            "BUNDLE_GITHUB__COM=${{ secrets.BUNDLE_GITHUB__COM }}:x-oauth-basic"
            "MAGLEV_ADMIN_USERNAME=${{ secrets.MAGLEV_ADMIN_USERNAME }}"
            "MAGLEV_ADMIN_PASSWORD=${{ secrets.MAGLEV_ADMIN_PASSWORD }}"
          push: true
          labels: |
            "service=${{ github.event.repository.name }}"
          tags: |
            "ghcr.io/${{ env.IMAGE_NAME }}:latest"
            "ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max 

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install kamal -v 1.3.1
    
      - name: Run deploy command
        run: |
          git status --porcelain
          kamal deploy --skip-push

      - uses: actions/delete-package-versions@v4
        with: 
          owner: "${{ github.repository_owner }}"
          package-name: "${{ github.event.repository.name }}"
          package-type: 'container'
          token: "${{ secrets.GITHUB_TOKEN }}"
          min-versions-to-keep: 3